"""Run one M4 graph session with a mock provider by default."""

from __future__ import annotations

import argparse
import asyncio
import json
from typing import Any

from harness.graph import build_mvp_graph
from harness.models.provider import MockProvider


def _mock_provider() -> MockProvider:
    return MockProvider(
        {
            "ProblemDesignOutput": {
                "problem_id": "demo-problem",
                "title": "Add two numbers",
                "statement": "Return the sum of two integers.",
                "constraints": ["Use Python."],
                "examples": [{"input": "1 2", "output": "3"}],
                "test_specification": [{"name": "basic"}],
                "difficulty": "beginner",
            },
            "CodeReviewOutput": {
                "correctness_analysis": "Review generated by the mock provider.",
                "detected_issues": [],
                "hints": ["Trace one example."],
                "pedagogical_feedback": "Check each loop iteration.",
                "confidence": 1.0,
            },
            "ExecutionRequest": {
                "language": "python",
                "source_code": "print('mock execution request')",
                "test_cases": [{"name": "basic"}],
                "timeout_seconds": 5,
            },
        }
    )


async def _run(message: str, thread_id: str, learner_code: str | None) -> dict[str, Any]:
    graph = build_mvp_graph(_mock_provider())
    return await graph.ainvoke(
        {"user_message": message, "learner_code": learner_code},
        {"configurable": {"thread_id": thread_id}},
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Run one M4 mock-provider session.")
    parser.add_argument("message", help="Learner request to route through the graph.")
    parser.add_argument("--thread-id", default="demo-session")
    parser.add_argument("--learner-code")
    arguments = parser.parse_args()
    result = asyncio.run(_run(arguments.message, arguments.thread_id, arguments.learner_code))
    print(json.dumps(result["final_output"], indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
